sudo: false

language: c

addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1

env:
  global:
    - PATH=$PATH:~/gcc-arm-none-eabi-5_2-2015q4/bin

install:
  - curl --location --output ~/gcc-arm-none-eabi.tar.bz2 --url https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-linux.tar.bz2
  - tar --extract --directory ~/ --file ~/gcc-arm-none-eabi.tar.bz2

script:
  - make --directory examples/simple
